version: '3'
services:
  stubby:
    build: ./stubby
    networks:
     - dns
    restart: unless-stopped
  unbound:
    build: ./unbound
    image: "mvance/unbound:1.13.1-stubby"
    depends_on:
      - "stubby"
      - "dnscrypt_proxy"
    ports:
     - "53:53/udp"
     - "53:53/tcp"
    networks:
     - dns
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    restart: unless-stopped
  dnscrypt_proxy:
    build: ./dnscrypt-proxy
    restart: always
    networks:
     - dns

networks:
  dns:
